name: ci
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 50
    steps:
    - uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 0
    - uses: olafurpg/setup-scala@v12
      with:
        java-version: "adopt@1.8"
    - uses: coursier/cache-action@v6
    - run: |
        mkdir -p ~/tmp/bin
        pushd ~/tmp/bin && wget -c https://chromedriver.storage.googleapis.com/2.44/chromedriver_linux64.zip && unzip chromedriver_linux64.zip && popd
        pushd ~/tmp/bin && wget -c https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz && tar -xzvf geckodriver-v0.24.0-linux64.tar.gz && popd
        chmod -vv +x ~/tmp/bin/*
        export PATH=$HOME/tmp/bin:$PATH
    - run: sbt -v "++ 3.0.1!" Test/compile test
